// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppleBlack: typeof import('C:/Coding/work-dot/src/components/Element/AppleBlack.vue')['default']
    AppleWhite: typeof import('C:/Coding/work-dot/src/components/Element/AppleWhite.vue')['default']
    ElementAppleBlack: typeof import('C:/Coding/work-dot/src/components/Element/AppleBlack.vue')['default']
    ElementAppleWhite: typeof import('C:/Coding/work-dot/src/components/Element/AppleWhite.vue')['default']
    ElementPlayStore: typeof import('C:/Coding/work-dot/src/components/Element/PlayStore.vue')['default']
    HelloWorld: typeof import('C:/Coding/work-dot/src/components/HelloWorld.vue')['default']
  }
}

export { }
