// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    AppHeaderStyle1: typeof import("C:/Coding/work-dot/src/components/AppHeader/Style1.vue")["default"]
    AppHeaderStyle2: typeof import("C:/Coding/work-dot/src/components/AppHeader/Style2.vue")["default"]
    AppHeaderStyle3: typeof import("C:/Coding/work-dot/src/components/AppHeader/Style3.vue")["default"]
    ElementAppleBlack: typeof import("C:/Coding/work-dot/src/components/Element/AppleBlack.vue")["default"]
    ElementAppleWhite: typeof import("C:/Coding/work-dot/src/components/Element/AppleWhite.vue")["default"]
    ElementPlayStore: typeof import("C:/Coding/work-dot/src/components/Element/PlayStore.vue")["default"]
    HelloWorld: typeof import("C:/Coding/work-dot/src/components/HelloWorld.vue")["default"]
    Stars: typeof import("C:/Coding/work-dot/src/components/Stars.vue")["default"]
  }
}

export {}
